title: Mingyang Kang's Homepage
page-top-title: Mingyang Kang
top-section-bg-text: Mathematics
home-subtitle: Mingyang Kang&ensp;|&ensp;康铭洋
copyright-text: '&copy; Mingyang Kang 2023-2025. All Rights Reserved.'
